name = "cf-pusher"
main = "src/index.ts"
compatibility_date = "2024-06-19"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "DO_PUSHER", class_name = "DOPusher" },
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["MyDurableObject"] # Array of new classes